# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodctl < Formula
  desc "search,check and update go modules"
  homepage "https://github.com/beatlabs/gomodctl"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/beatlabs/gomodctl/releases/download/v0.3.0/gomodctl_Darwin_x86_64.tar.gz"
    sha256 "153f1e2d446e914f17ed68281583724eb04922071efe1ff101ce29a93d57657c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/beatlabs/gomodctl/releases/download/v0.3.0/gomodctl_Linux_x86_64.tar.gz"
      sha256 "fd0d8be1798d2e8ab770efeac2b81b981faef12cdd2f850d64962a32bf5e9fa0"
    end
  end

  def install
    bin.install "gomodctl"
  end

  test do
    system "#{bin/gomodctl}"
  end
end
