# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodctl < Formula
  desc "search,check and update go modules"
  homepage "https://github.com/beatlabs/gomodctl"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/beatlabs/gomodctl/releases/download/v0.0.5/gomodctl_Darwin_x86_64.tar.gz"
    sha256 "c3530ff78f1f033b334c67ac321ed5377f9dba6bc25b0ded13b8b2eefdf91c92"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/beatlabs/gomodctl/releases/download/v0.0.5/gomodctl_Linux_x86_64.tar.gz"
      sha256 "99b9e14bf4f3fca047c3226edf0936de52a92fcc6b945cf1091e7ebaa54f7e37"
    end
  end

  def install
    bin.install "gomodctl"
  end

  test do
    system "#{bin/gomodctl info gomock}"
  end
end
